"""empty message

Revision ID: 0b8e977a88b6
Revises: 49625d3e160e
Create Date: 2023-01-02 23:30:07.395057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8e977a88b6'
down_revision = '49625d3e160e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.String(), nullable=False),
    sa.Column('certificate_name', sa.String(), nullable=False),
    sa.Column('certificate_issuer', sa.String(), nullable=False),
    sa.Column('certificte_image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certifications'))
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact'))
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Start_year', sa.DATETIME(), nullable=False),
    sa.Column('End_year', sa.DATETIME(), nullable=False),
    sa.Column('Instituition', sa.String(), nullable=False),
    sa.Column('Location', sa.String(), nullable=False),
    sa.Column('Qualification', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_education'))
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Company_uuid', sa.String(), nullable=False),
    sa.Column('Company_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experience'))
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('Proficiency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_link', sa.String(), nullable=False),
    sa.Column('project_image', sa.String(), nullable=False),
    sa.Column('project_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Hero_content', sa.Text(), nullable=False),
    sa.Column('About_content', sa.Text(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('linkedin', sa.String(), nullable=False),
    sa.Column('Work_content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume'))
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('skill_icon', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Role_uid', sa.String(), nullable=False),
    sa.Column('Start_year', sa.DATETIME(), nullable=False),
    sa.Column('End_year', sa.String(), nullable=False),
    sa.Column('Role_name', sa.String(), nullable=False),
    sa.Column('Role_description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['Role_uid'], ['experience.Company_uuid'], name=op.f('fk_roles_Role_uid_experience')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.drop_table('editorspick')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editorspick',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Post_id', sa.VARCHAR(), nullable=False),
    sa.Column('Date_Registered', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_editorspick'),
    sa.UniqueConstraint('Post_id', name='uq_editorspick_Post_id')
    )
    op.drop_table('roles')
    op.drop_table('skills')
    op.drop_table('resume')
    op.drop_table('projects')
    op.drop_table('languages')
    op.drop_table('experience')
    op.drop_table('education')
    op.drop_table('contact')
    op.drop_table('certifications')
    # ### end Alembic commands ###
