"""empty message

Revision ID: 0fcd2ec9563e
Revises: 8dfdca2c8f8c
Create Date: 2023-02-01 00:48:43.789340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fcd2ec9563e'
down_revision = '8dfdca2c8f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Certificate_uid', sa.String(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_certifications_Certificate_uid'), ['Certificate_uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_certifications_Certificate_uid'), type_='unique')
        batch_op.drop_column('Certificate_uid')

    # ### end Alembic commands ###
