"""empty message

Revision ID: 49625d3e160e
Revises: 91a7b2f6cb2d
Create Date: 2022-12-31 00:12:19.511075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49625d3e160e'
down_revision = '91a7b2f6cb2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_posts')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Image', sa.String(), nullable=True))
        batch_op.drop_column('Videos')
        batch_op.drop_column('Audios')
        batch_op.drop_column('Images')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Images', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('Audios', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('Videos', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('Image')

    op.create_table('_alembic_tmp_posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Image', sa.VARCHAR(), nullable=False),
    sa.Column('Category', sa.VARCHAR(), nullable=False),
    sa.Column('Post_Type', sa.VARCHAR(), nullable=False),
    sa.Column('Post_Uuid', sa.VARCHAR(), nullable=False),
    sa.Column('Content', sa.TEXT(), nullable=False),
    sa.Column('Title', sa.VARCHAR(), nullable=False),
    sa.Column('is_draft', sa.BOOLEAN(), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.Column('Author_uid', sa.VARCHAR(), nullable=True),
    sa.Column('Date_Posted', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['Author_uid'], ['blogger.Blogger_id'], ),
    sa.PrimaryKeyConstraint('id', name='pk_posts'),
    sa.UniqueConstraint('Post_Uuid', name='uq_posts_Post_Uuid')
    )
    # ### end Alembic commands ###
