"""empty message

Revision ID: 75c59fa3b3be
Revises: 4262f9067013
Create Date: 2022-12-27 18:16:54.722940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c59fa3b3be'
down_revision = '4262f9067013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('is_published')
        batch_op.drop_column('is_draft')

    # ### end Alembic commands ###
