"""empty message

Revision ID: 8dfdca2c8f8c
Revises: cf91172db1c3
Create Date: 2023-01-16 11:54:22.289535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfdca2c8f8c'
down_revision = 'cf91172db1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Company_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('Company_url')

    # ### end Alembic commands ###
