"""empty message

Revision ID: a738c4bb5376
Revises: c6246e0e79ff
Create Date: 2023-02-07 19:54:15.386645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a738c4bb5376'
down_revision = 'c6246e0e79ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Contact_id', sa.String(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact')),
    sa.UniqueConstraint('Contact_id', name=op.f('uq_contact_Contact_id'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Project_id', sa.String(), nullable=False),
    sa.Column('Project_title', sa.String(), nullable=False),
    sa.Column('Project_link', sa.String(), nullable=False),
    sa.Column('Project_image', sa.String(), nullable=False),
    sa.Column('Project_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('Project_id', name=op.f('uq_projects_Project_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('contact')
    # ### end Alembic commands ###
