"""empty message

Revision ID: aeadd3f18b5c
Revises: fa5017571558
Create Date: 2023-02-13 23:14:16.340472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeadd3f18b5c'
down_revision = 'fa5017571558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Read', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('Received', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('Received')
        batch_op.drop_column('Read')

    # ### end Alembic commands ###
