"""empty message

Revision ID: c6246e0e79ff
Revises: 0fcd2ec9563e
Create Date: 2023-02-07 19:53:02.589131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6246e0e79ff'
down_revision = '0fcd2ec9563e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Project_id', sa.VARCHAR(), nullable=False),
    sa.Column('Project_link', sa.VARCHAR(), nullable=False),
    sa.Column('Project_image', sa.VARCHAR(), nullable=False),
    sa.Column('Project_description', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_projects'),
    sa.UniqueConstraint('Project_id', name='uq_projects_Project_id')
    )
    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Contact_id', sa.VARCHAR(), nullable=False),
    sa.Column('Name', sa.VARCHAR(), nullable=False),
    sa.Column('Email', sa.VARCHAR(), nullable=False),
    sa.Column('Message', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_contact'),
    sa.UniqueConstraint('Contact_id', name='uq_contact_Contact_id')
    )
    # ### end Alembic commands ###
