"""empty message

Revision ID: fa5017571558
Revises: a738c4bb5376
Create Date: 2023-02-13 05:24:36.648677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5017571558'
down_revision = 'a738c4bb5376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_uuid', sa.String(), nullable=False))
        batch_op.drop_constraint('uq_settings_settin_uuid', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_settings_setting_uuid'), ['setting_uuid'])
        batch_op.drop_column('settin_uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settin_uuid', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_settings_setting_uuid'), type_='unique')
        batch_op.create_unique_constraint('uq_settings_settin_uuid', ['settin_uuid'])
        batch_op.drop_column('setting_uuid')

    # ### end Alembic commands ###
